### ISSUE TITLE
Emoji réactions : proposition de CSS amélio

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#257]
La feature est jeune, mais voici une suggestion sans prétention pour améliorer son intégration visuelle : 

![image](https://github.com/NextINpact/Next/assets/48727868/f641a084-a1e0-473e-88eb-6e3e48fdbc91)

```css
.emoji-reaction-list button {
    border-radius: 0.3rem;
    border: 1px solid midnightblue;
    /* j'avais pas le code couleur exact en tête, 
       mais mettre une peu contrastée pour éviter
       que ça ne fasse tache me semble idéale */
    padding: 0.3rem 0.5rem 0.3rem 0.5rem;
}
```

J'ai aussi augmenté la `margin` dans `.emoji-reaction-list button` à 10 et `gap` à 6.
