### ISSUE TITLE
Police manquante : source code pro

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/Next#267]
La police référencée pour l'inclusion de code dans les articles n'est pas chargée. Résultat des courses : la police est la police classique de l'article, au lieu d'être la police monospace source-code-pro.

Du coup, c'est la police SourceSansProRegular qui est utilisée (la même que pour l'article).

Suggestion : 
- charger la police correspondante
- changer le CSS pour utiliser une police "de secours" qui soit monospace.

On peut voir les problèmes de police sur un article comme celui-ci : https://next.ink/117581/guacamole-sur-un-plateau-5-5-on-passe-a-deux-facteurs-et-cest-termine/

Toutes les commandes listées  sont sensées être en SourceCodePro.

**Comment by Cqoicebordel** [comment]
Le problème est pas la police en tant que telle. Ca vient de la feuille de style de Wordpress.

En effet, dans le `style.css` de Next, y'a 
```css
code {
    font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
        monospace;
}
```

Le problème vient de la feuille de `style style.min.css?ver=6.4.2` qui contient : 
```css
.wp-block-code code {
    display: block;
    font-family:inherit;
    overflow-wrap: break-word;
    white-space: pre-wrap
}
```

Si on commente la ligne `font-family:inherit;` tout fonctionne correctement.

Une autre solution, moins propre, mais plus simple, probablement, est de rajouter un `!important` à la find de la ligne sur les fonts : 
```css
code {
    font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
        monospace !important;
}
```

Mais ça n'empêche pas que, évidemment, la police source-code-pro n'est effectivement pas chargée. Mais au moins, avec ces changements, pour moi ça retombe sur du Courrier New, qui fait le job.
