### ISSUE TITLE
Message "prévisualisation" qui déborde sur le texte

### ISSUE THREAD

**Issue by Wivik** [NextINpact/Next#282]
Une dernière pour l'année (j'espère :grin: ), en mode prévisualisation le message déborde sur le texte : 

![image](https://github.com/NextINpact/Next/assets/48727868/0d0f91f2-4ce7-45b6-9b8a-4e601be7b9df)

Un petit `padding-bottom` semble faire le taff : 

![image](https://github.com/NextINpact/Next/assets/48727868/dbe35e0f-8434-4586-ad35-a212160e801f)

```css
#comment-editor-wrapper #input-output #output-area {
    background: rgba(255,255,255,0);
    border-radius: 5px 5px 0px 0px;
    display: none;
    overflow-y: scroll;
    scrollbar-width: none;
    -ms-overflow-style: none;
    flex-grow: 1;
    font: normal normal normal 0.875rem/1rem sans-serif;
    line-height: 14px;
    min-height: 60px;
    color: #242424;
    padding-bottom: 2rem; /* <<<<<<< */
}
```
